spring:
    mvc:
      pathmatch:
          matching-strategy: ant_path_matcher
    datasource:
        username: postgres
        password: mysecretpassword
        url: jdbc:postgresql://localhost:5432/postgres
    flyway:
        enabled: true
        locations: classpath:/db/migration
        schemas: postgres
        password: mysecretpassword
        user: postgres
        baseline-on-migrate: true
        url: jdbc:postgresql://localhost:5432/postgres

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: public
